### ISSUE TITLE
Unexpected error fetching soma_connect data: unsupported operand type(s) for -: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by ziptbm** [Djelibeybi/hass-soma-connect#33]
Replaced an original "2" device with a replacement "2" device, and then with a "2C" device per Soma support.  Following these changes, I'm now seeing this error with the integration and only getting 1 device in Home Assistant.

```
This error originated from a custom integration.

Logger: custom_components.soma_connect.coordinator
Source: custom_components/soma_connect/coordinator.py:127
Integration: SOMA Connect (documentation, issues)
First occurred: 10:51:54 (37 occurrences)
Last logged: 11:27:26

Unexpected error fetching soma_connect data: unsupported operand type(s) for -: 'int' and 'NoneType'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/soma_connect/coordinator.py", line 127, in _async_update_data
    self._positions[shade.mac] = int(100 - shade.position)
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
```

One interesting thing to note is that the older devices and macs show when I visit the <ip>:3000/list_devices page, so I'm wondering if there's some sort of conflict or issue with devices that are named "null" or "old" as I see in the list.  I first reset them via Smart Shades and then after that removed them from the app, but they're still showing in the list from Soma Connect.

Any pointers?  Anything else I should look for that might be causing this issue?

Also, an interesting note is that the newer "2C" devices show up as gen "1" via Soma Connect but show as 2S in the Smart Shades app.  All devices are on firmware 2.3.3 and Soma Connect is on 2.3.1.  If I disable this version and go with the native SOMA Connect app, it appears to correctly show the only 6 shades I have connected (despite the list_devices api showing 4 more that are no longer connected), but also has "<unknown>" for the model on each unit.

**Comment by Djelibeybi** [comment]
It's not getting a position value, i.e. `shade.position` is empty. I'll need to add some debug logs and give you a version so I can see what results you're getting.
