### ISSUE TITLE
USB Bridge is not found

### ISSUE THREAD

**Issue by Vollerplasc** [Djelibeybi/hass-soma-connect#47]
Hello, I installed the version on me and I entered the IP address of the bridge, which in the meantime is already the USB stick, but unfortunately it is not recognized. I tried the last version and the beta version

**Comment by Djelibeybi** [comment]
This plugin doesn't support the newer USB stick, only the older Raspberry Pi based version.

**Comment by Vollerplasc** [comment]
Will there be a version that supports the USB stick? I would like to have the battery levels displayed.

**Comment by Djelibeybi** [comment]
Unlikely unless I get one myself, I suspect.

**Comment by stleusc** [comment]
I was wondering the same....
I do have a USB version. To support it, some changes would be required.
Not sure how hard it would be to create a cloned repo based on your code and make the changes and then publish that.
Also not sure what your thoughts are about using your codebase....

**Comment by Vollerplasc** [comment]
Some time ago I wrote to the manufacturer of the roller blind drives, because in HA is always displayed 100%, which is not true.
I was sent the following lines to solve the problem.

Hello Volker,
 
Thank you for contacting us. Somebody made some changes in HA and after that it started showing the 100%. We will probably be able to fix it in autumn. 
If you would like to try yourself, you can use these examples to set up a REST sensor in HA. If you have the USB Connect you can use these as they are (with your own device IP and MAC). Check out the SOMA API description on our support pages and HA REST sensor examples on their website.
 
‘‘‘sensor:   
-platform: rest     
name: V3 Battery mv     
resource: "http://192.168.0.114:3000/get_battery_level?mac=c3:8a:47:39:ba:c0"     
value_template: ''     
unit_of_measurement: "mV"     
scan_interval: 300
 
sensor:  
 - platform: rest     
name: V3 Battery percent     
resource: "http://192.168.0.114:3000/get_battery_level?mac=c3:8a:47:39:ba:c0"     
value_template: ''     
unit_of_measurement: "%"     
scan_interval: 300‘‘‘

**Comment by Djelibeybi** [comment]
> Also not sure what your thoughts are about using your codebase

Go nuts. :) This is why I released it under a permissive license.
