### ISSUE TITLE
Request: Support sensor for position and battery voltage

### ISSUE THREAD

**Issue by stleusc** [Djelibeybi/hass-soma-connect#79]
/get_shade_state/"MAC" : This endpoint needs a MAC address from the list. The MAC address can be copied in the format it appears in the list (for example: http://192.168.0.104:3000/get_shade_state/dd:9b:89:47:a5:e7). This will return the current position of the shade. Position is in the range 0..100

Especially nice to poll that every 1s while the shades are moving!

/get_battery_level/"MAC" : This endpoint returns the current battery level from the device. The battery level is in units of 10 mV. The battery level should usually be between 360 and 410. Anything under 320 is critically low. The device itself considers 360 the minimum to move the motor - anything under this will reject all motion commands.

**Comment by stleusc** [comment]
OK, never mind on the polling... they provide the position that we are commanding. So if sending close, they report close right away. STUPID!
Especially since the data is available, their app shows the blinds moving.

Well battery level is kinda optional I guess. So feel free to ignore that one too hahaha.

Nice job on the add-on though!


It took me an hour to get the soma connect SW running on my PI without flashing their image. My Pi is running Ubuntu 64bit. So some trickery was needed. But now it works and I am happy!

**Comment by Djelibeybi** [comment]
The battery level isn't accurate anyway: not beyond the documented lower limit of 320.
